name: 'decK action'
description: 'Declarative Configuration management for Kong'
inputs:
  command:
    description: 'A decK command you want to execute'
    required: true
    default: 'ping'
  runtime_group:
    description: 'Targetted Runtime'
    required: true
    default: 'default'
  options:
    description: 'Option parameters for a decK command'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.runtime_group }}
    - ${{ inputs.options }}
