name: Sync
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: decK ping
      id: decK_ping
      uses: ./
      with:
        command: "ping"
        options: "--konnect-token ${{ secrets.System_Account_Token }}"
    - name: decK validate
      id: decK_validate
      uses: ./
      with:
        command: "validate"
        options: "--konnect-token ${{ secrets.System_Account_Token }} " 
        runtime_group: "lob_dev"
    - name: decK sync
      id: decK_sync
      uses: ./
      with:
        command: "sync"
        options: "--konnect-token ${{ secrets.System_Account_Token }}" 
        runtime_group: "lob_dev"
